{
  "train_batch_size": 128,
  "steps_per_print": 10000000000,
  "optimizer": {
    "type": "SGD",
    "params": {
      "lr": 0.01,
      "momentum": 0.9,
      "weight_decay": 5.e-4
    }
  },
  "gradient_clipping": 1.0,
  "prescale_gradients": False,
  "bf16": {
      "enabled": false
  },
  "fp16": {
      "enabled": true,
      "fp16_master_weights_and_grads": False,
      "loss_scale": 0,
      "loss_scale_window": 500,
      "hysteresis": 2,
      "min_loss_scale": 1,
      "initial_scale_power": 15
  },
  "wall_clock_breakdown": False,
  "zero_allow_untested_optimizer": true,
  "zero_optimization": {
        "stage": 3,
        "contiguous_gradients": true,
        "stage3_max_live_parameters": 1.e+9,
        "stage3_max_reuse_distance": 1.e+9,
        "stage3_prefetch_bucket_size": 1.e+7,
        "stage3_param_persistence_threshold": 1.e+5,
        "reduce_bucket_size": 1.e+7,
        "sub_group_size": 1.e+9,
        "offload_optimizer": {
            "device": "cpu"
         },
        "offload_param": {
            "device": "cpu"
       }
   }
    
}